opt.colors = ['r', 'b', 'g', 'k'];
opt.tStart = 30;
opt.tStop = 60;
opt.FontSize = 20;

fig = figure('Name', 'LM2500');
fig.OuterPosition = fig.InnerPosition;
hold on;

plot(getsampleusingtime(simResults(3).sim.Results.max.ES.Pout,opt.tStart,opt.tStop), ...
    'Color', opt.colors(1), ...
    'LineStyle',':', ...
    'LineWidth',2, ....
    'DisplayName','2 WTs');

plot(getsampleusingtime(simResults(5).sim.Results.max.ES.Pout,opt.tStart,opt.tStop), ...
    'Color', opt.colors(2), ...
    'LineStyle','--', ...
    'LineWidth',2, ....
    'DisplayName','3 WTs');

plot(getsampleusingtime(simResults(7).sim.Results.max.ES.Pout,opt.tStart,opt.tStop), ...
    'Color', opt.colors(3), ...
    'LineStyle','-.', ...
    'LineWidth',2, ....
    'DisplayName','4 WTs');

title('Energy Storage Output for LM2500 cases');
ylabel('Output power [MW]', 'FontSize', opt.FontSize);
xlabel('Time [s]', 'FontSize', opt.FontSize);
legend('Location', 'best','Orientation','horizontal');

axis([opt.tStart, opt.tStop, -inf, inf]);

fig = figure('Name', 'LM6000');
fig.OuterPosition = fig.InnerPosition;
hold on;

plot(getsampleusingtime(simResults(10).sim.Results.max.ES.Pout,opt.tStart,opt.tStop), ...
    'Color', opt.colors(1), ...
    'LineStyle',':', ...
    'LineWidth',2, ....
    'DisplayName','2 WTs');

plot(getsampleusingtime(simResults(12).sim.Results.max.ES.Pout,opt.tStart,opt.tStop), ...
    'Color', opt.colors(2), ...
    'LineStyle','--', ...
    'LineWidth',2, ....
    'DisplayName','3 WTs');

plot(getsampleusingtime(simResults(14).sim.Results.max.ES.Pout,opt.tStart,opt.tStop), ...
    'Color', opt.colors(3), ...
    'LineStyle','-.', ...
    'LineWidth',2, ....
    'DisplayName','4 WTs');

title('Energy Storage Output for LM6000 cases');
ylabel('Output power [MW]', 'FontSize', opt.FontSize);
xlabel('Time [s]', 'FontSize', opt.FontSize);
legend('Location', 'best','Orientation','horizontal');

axis([opt.tStart, opt.tStop, -inf, inf]);


hold off;